version: "2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - "3000:3000"